route:
  receiver: "email"

receivers:
  - name: "email"
    email_configs:
      - to: "your-email@example.com"
        from: "alert@example.com"
        smarthost: "smtp.gmail.com:587"
        auth_username: "your-email@example.com"
        auth_password: "your-password"